#!/bin/bash
#PBS -V
#PBS -l nodes=1:ppn=12
#PBS -q batch
#PBS -j oe
#PBS -l walltime=120:00:00

#  export GAUSS_SCRDIR=/home/shuo/scratch

GAUSS_SCRDIR=/scratch/shuo/g09
module load gaussian/g09





date
time g09 < /scratch/shuo/100/ing/27_C20H13N3SSi/G09/27_C20H13N3SSi.gjf > /scratch/shuo/100/ing/27_C20H13N3SSi/G09/27_C20H13N3SSi.out
date
mv /scratch/shuo/100/ing/27_C20H13N3SSi /scratch/shuo/100/result/ 
