#!/bin/bash


# Top1000 moleculess'
# Data processing

# put into any folder with two tempelate files, no parameter needed. Upon running, generate the input for octopus td calculation (three folders for three directions)
# from octopus gs calculation and put it into a new subfolder (called octopus_td) in the same sub folder. Then generate submission script and submit job.
#
#
# Author Shuo Dai
# Verstion: 20140109
#
#


# submitted the G09 job for the files in the $some/ing/ folder and after finishing it, move the folder into $some/result/1_C60/G09 folder
# moved and submitted the gs job for the files in the $some/result/ (create octopus_gs folder) and after finishing it, move the folder into $some/octopus/1_C60/octopus_gs
# submitted the td job for the files in the folder $some/octopus (create 1_C60/octopus_td_x/y/z) and after finishing it, move the folder into $some/octopus_td
# before finishing it ,move the data into $some/finish and then calculate absorption spectra for the files in the $some/finish and leave a log which file has been processed.



# CHANGE HERE !! 1/3
base_dir='/scratch/shuo/1kb/finish4';

# CHANGE HERE !! 2/3 (to accquire the filename) the string that should not in the xyz filename(the path part)
char_to_cut="/scratch/shuo/1kb/finish4/"

# CHANGE HERE !! 3/3 tempelate files are stored in the same directory as this scripts (inp_td_tempelate and submit.octopus.tempelate)
current_dir=$PWD




# 	search for file 
# 	for folder in 'find $base_dir -type f'

# 	search for folder 

# find the subfolder that contains G09 so we could locate its father folder in the next step in order to set up a new octopus_td folder.
for folder in `find $base_dir -type d -print | grep "G09"`

do
	
#  Confirmation of the folder and set up folder for three directions
	echo $folder
	last_level=${folder%%/G09*}
	echo $last_level
	mkdir $last_level/abs_spectra
	cd $folder

#  extract xyz filename
	xyz_filename=${folder#*${char_to_cut}}
	xyz_filename=${xyz_filename%%/G09*}
	
	echo $xyz_filename

#  copy the multipole files to the same folder with the inp file to calculate the absorption vector
	echo "copying multipole files from td."
	cp -f $last_level/octopus_td_x/td.general/multipoles $last_level/abs_spectra/multipoles.1
	cp -f $last_level/octopus_td_y/td.general/multipoles $last_level/abs_spectra/multipoles.2
	cp -f $last_level/octopus_td_z/td.general/multipoles $last_level/abs_spectra/multipoles.3
	cp -f $HOME/Template/top1000/inp_for_abs_calculation $last_level/abs_spectra/inp

# calculate the abroption using utility program
	cd $last_level/abs_spectra
	echo "calculating the $xyz_filename."
	echo $PWD
	time /opt/octopus/4.1.0/bin/oct-propagation_spectrum >> ${xyz_filename}_abs_cs10fs.log && echo "$(date -d  today +%Y%m%d%H%M)_$xyz_filename" >> $base_dir/log
	
	sleep 3

done

echo "Job finished."
