#!/bin/bash


# Top1000 moleculess'
# Step 3/3

# put into any folder with two tempelate files, no parameter needed. Upon running, generate the input for octopus td calculation (three folders for three directions)
# from octopus gs calculation and put it into a new subfolder (called octopus_td) in the same sub folder. Then generate submission script and submit job.
#
#
# Author Shuo Dai
# Verstion: 20140105
#
#

# submitted the G09 job for the files in the $some/ing/ folder and after finishing it, move the folder into $some/result/1_C60/G09 folder
# moved and submitted the gs job for the files in the $some/result/ (create octopus_gs folder) and after finishing it, move the folder into $some/octopus/1_C60/octopus_gs
# submitted the td job for the files in the folder $some/octopus (create 1_C60/octopus_td_x/y/z) and after finishing it, move the folder into $some/octopus_td
# calculate absorption spectra for the files in the $some/octopus_td and after finishing it ,move the folder into $some/finish


# CHANGE HERE!! 0/3 the file will move from "start" to "target" upon finish
start=octopus_td_group1


# CHANGE HERE !! 1/3
base_dir="/scratch/shuo/400/${start}";

# CHANGE HERE !! 2/3 (to accquire the filename) the string that should not in the xyz filename(the path part)
char_to_cut="/scratch/shuo/400/$start/"

# CHANGE HERE !! 3/3 tempelate files are stored in the same directory as this scripts (inp_td_tempelate and submit.octopus.tempelate)
current_dir=$PWD





# 	search for file 
# 	for folder in 'find $base_dir -type f'

# 	search for folder 

# find the subfolder that contains G09 so we could locate its father folder in the next step in order to set up a new octopus_td folder.
for folder in `find $base_dir -type d -print | grep "G09"`

do
	
#  Confirmation of the folder and set up folder for three directions
	echo $folder
	last_level=${folder%%/G09*}
	echo $last_level
	mkdir $last_level/octopus_td_x
	mkdir $last_level/octopus_td_y
	mkdir $last_level/octopus_td_z


#  extract xyz filename
	
	
	xyz_filename=${folder#*${char_to_cut}}
	xyz_filename=${xyz_filename%%/G09*}
	
	echo $xyz_filename






#  prepare the td_y folder (copy gs files and generate the td_y input)
	echo "copying file from gs to td_y: $last_level/octopus_td_y"
	cp -rf $last_level/octopus_gs/* $last_level/octopus_td_y
	sleep 2
	cd $last_level/octopus_td_y
	rm -f *.log
	rm -f submit*
	rm inp

# generate the td_y input from the tempelate
	echo "generating inp for td y-direction: $last_level/octopus_td_y"
	cp $current_dir/inp_td_tempelate $last_level/octopus_td_y/inp
	echo "XYZCoordinates = '${xyz_filename}_G09opt.xyz'" >> $last_level/octopus_td_y/inp
	echo "TDPolarizationDirection = 2" >> $last_level/octopus_td_y/inp
	echo -e ""
	echo "The last two line:"
	tail -2 $last_level/octopus_td_y/inp
	echo -e ""


#  generate the submission script for td input

#  the name of submission script
script_name=submit_${xyz_filename}
result_name=${xyz_filename}_td_y.log
	echo "generating and submitting the script: $last_level/octopus_td_x/$script_name"
	cp $current_dir/submit.octopus.tempelate $last_level/octopus_td_y/$script_name
	echo "cd $last_level/octopus_td_y/" >> $last_level/octopus_td_y/$script_name
	echo "time octopus < $last_level/octopus_td_y/inp >  $last_level/octopus_td_y/$result_name" >> $last_level/octopus_td_y/$script_name
	echo "date" >> $last_level/octopus_td_y/$script_name

#  submit the script

echo "Submitting job - ${xyz_filename}_td_y"  && qsub $last_level/octopus_td_y/$script_name
echo "Sleeping a few seconds before submitting next job..." && sleep 3



done
