#!/bin/bash
#PBS -V
#PBS -l nodes=1:ppn=12
#PBS -q batch
#PBS -j oe
#PBS -l walltime=120:00:00

#  export GAUSS_SCRDIR=/home/shuo/scratch

GAUSS_SCRDIR=/scratch/shuo/g09
module load gaussian/g09





date
time g09 < /scratch/shuo/100/ing/47_C19H11N3OS2SeSi/G09/47_C19H11N3OS2SeSi.gjf > /scratch/shuo/100/ing/47_C19H11N3OS2SeSi/G09/47_C19H11N3OS2SeSi.out
date
mv /scratch/shuo/100/ing/47_C19H11N3OS2SeSi /scratch/shuo/100/result/ 
