#!/bin/bash
#PBS -V
#PBS -l nodes=1:ppn=12
#PBS -q batch
#PBS -j oe
#PBS -l walltime=120:00:00

#  export GAUSS_SCRDIR=/home/shuo/scratch

GAUSS_SCRDIR=/scratch/shuo/g09
module load gaussian/g09





date
time g09 < /scratch/shuo/100/ing/29_C22H10N4S4Si/G09/29_C22H10N4S4Si.gjf > /scratch/shuo/100/ing/29_C22H10N4S4Si/G09/29_C22H10N4S4Si.out
date
mv /scratch/shuo/100/ing/29_C22H10N4S4Si /scratch/shuo/100/result/ 
